In [77]:
import pandas as pd
from IPython.display import display

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [78]:
# create a function for summarising values in a dataframe

def summarise_df(df: pd.DataFrame,
                column_info_page_views_and_duration_list:list=column_info_page_views_and_duration_list,
                column_info_google_analytics_list:list=column_info_google_analytics_list, 
                column_info_time_categories_list:list=column_info_time_categories_list) -> list:
    
    # Create four empty dicts according the category groups outlined earlier
    # We will in the loops below add summarised values from each column to these dicts.
    column_info_page_views_and_duration_summary = {}
    column_info_google_analytics_summary = {}
    column_info_time_categories_summary = {}
    column_info_misc_categories_summary = {}

    # Iterate over each column in the session DataFrame
    for col in df.columns:

        # The Pandas API types module provides efficient functions for checking datatypes.
        # First lets check if the column contains numerical values.
        if pd.api.types.is_numeric_dtype(df[col]):

            # Next lets check which category grouping it belongs to.
            if col in column_info_page_views_and_duration_list:

                # For numerical regression data we want to know the max, min, mean values and the standard deviation
                column_info_page_views_and_duration_summary[col] = {
                                    'data_type' : df[col].dtype,
                                    'max_value' : df[col].max(),
                                    'min_value' : df[col].min(),
                                    'mean_value' : df[col].mean(),
                                    'standard_deviation' : df[col].std()
                                    }
                
            elif col in column_info_google_analytics_list:

                column_info_google_analytics_summary[col] = {
                                    'data_type' : df[col].dtype,
                                    'max_value' : df[col].max(),
                                    'min_value' : df[col].min(),
                                    'mean_value' : df[col].mean(),
                                    'standard_deviation' : df[col].std()
                                    }
                
            elif col in column_info_time_categories_list:

                column_info_time_categories_summary[col] = {
                                    'data_type' : df[col].dtype,
                                    'max_value' : df[col].max(),
                                    'min_value' : df[col].min(),
                                    'mean_value' : df[col].mean(),
                                    'standard_deviation' : df[col].std()
                                    }
            else:
                # For classification data, numerical or object, we want to know the unique values, their counts (including NaNs!) and top & bottom
                list_of_tuples_of_key_value_pairs_from_value_counts = [(key, int(value)) for key, value in df[col].value_counts(dropna=False).to_dict().items()]
                column_info_misc_categories_summary[col] = {
                                    'data_type' : df[col].dtype,
                                    'unique_values' : df[col].unique(),
                                    'value_counts' : list_of_tuples_of_key_value_pairs_from_value_counts,
                                    'top_value' : list_of_tuples_of_key_value_pairs_from_value_counts[0],
                                    'bottom_value' : list_of_tuples_of_key_value_pairs_from_value_counts[-1]
                                    }
        
        else:
            list_of_tuples_of_key_value_pairs_from_value_counts = [(key, int(value)) for key, value in df[col].value_counts(dropna=False).to_dict().items()]
            column_info_misc_categories_summary[col] = {
                                    'data_type' : df[col].dtype,
                                    'unique_values' : df[col].unique(),
                                    'value_counts' : list_of_tuples_of_key_value_pairs_from_value_counts,
                                    'top_value' : list_of_tuples_of_key_value_pairs_from_value_counts[0],
                                    'bottom_value' : list_of_tuples_of_key_value_pairs_from_value_counts[-1]
                                    }

    # convert summary dicts into dataframes for better visualisation   
    page_views_and_duration_summary_df = pd.DataFrame(column_info_page_views_and_duration_summary)  
    column_info_google_analytics_summary_df = pd.DataFrame(column_info_google_analytics_summary)
    column_info_time_categories_summary_df = pd.DataFrame(column_info_time_categories_summary)
    column_info_misc_categories_summary_df = pd.DataFrame(column_info_misc_categories_summary)

    summary_dfs_list = [page_views_and_duration_summary_df, column_info_google_analytics_summary_df, column_info_time_categories_summary_df, column_info_misc_categories_summary_df]
    
    # display dataframes with HTML in notebooks using the display method
    for df in summary_dfs_list:

        display(df)
    # display(page_views_and_duration_summary_df)
    # display(column_info_google_analytics_summary_df)
    # display(column_info_time_categories_summary_df)
    # display(column_info_misc_categories_summary_df)

    return summary_dfs_list

In [79]:
session_data_df = pd.read_csv('project_data.csv')

column_descriptions = {
                    "Administrative" : "Number of page visits within this category",
                    "Administrative_Duration" : "Time spent within this category",
                    "Informational" : "Number of page visits within this category",
                    "Informational_Duration" : "Time spent within this category", 
                    "ProductRelated" : "Number of page visits within this category", 
                    "ProductRelated_Duration" : "Time spent within this category",
                    "BounceRates" : "Bounce rate of current page",
                    "ExitRates" : "Exit rate value of current page",
                    "PageValues" : "Page value of current page",
                    "SpecialDay" : "Proximity in time of the session to a special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8.",
                    "Month" : "Month of session",
                    "Weekend" : "Boolean if the session day was in the weekend",
                    "OperatingSystems" : "Different OS' represented by different integers",
                    "Browser" : "Different browsers represented by different integers",
                    "Region" : "Different regions represented by different integers",
                    "TrafficType" : "Different traffic types represented by different integers",
                    "VisitorType" :  "Different visitor types represented by different categorical values",
                    }

column_info_page_views_and_duration_list = ['Administrative', 'Administrative_Duration', 'Informational','Informational_Duration', 'ProductRelated','ProductRelated_Duration']
column_info_google_analytics_list = ['BounceRates','ExitRates','PageValues']
column_info_time_categories_list = ['SpecialDay', 'Month', 'Weekend']
column_info_misc_categories_list = ['OperatingSystems','Browser','Region','TrafficType','VisitorType']

In [80]:
summarise_df(session_data_df, column_info_page_views_and_duration_list, column_info_google_analytics_list, column_info_time_categories_list)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration
data_type,int64,float64,int64,float64,int64,float64
max_value,27,989493.0,24,2549.375,705,63973.52223
min_value,-10,0.0,0,0.0,0,0.0
mean_value,2.2382,1269.776004,0.503569,34.472398,31.731468,1194.74622
standard_deviation,3.409269,34071.46693,1.270156,140.749294,44.475503,1913.669288

                   BounceRates ExitRates  PageValues
data_type              float64   float64     float64
max_value             2.098952       0.2  361.763742
min_value             -0.49868       0.0         0.0
mean_value            0.044239  0.043073    5.889258
standard_deviation    0.239735  0.048597   18.568437

                   SpecialDay
data_type             float64
max_value                 1.0
min_value                 0.0
mean_value            0.06126
standard_deviation    0.19865

,Unnamed: 0,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
data_type,int64,object,int64,float64,float64,int64,object,object,object
unique_values,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[Feb, Mar, May, Turc, Oct, June, Jul, Aug, Nov...","[1, 2, 4, 3, 7, 6, 8, 5]","[nan, 2.0, 1.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0,...","[1.0, nan, 2.0, 3.0, 4.0, 9.0, 5.0, 6.0, 7.0, ...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Returning_Visitor, New_Visitor, Other]","[False, True, Name:Zara]","[False, nan, True]"
value_counts,"[(12329, 1), (0, 1), (1, 1), (2, 1), (3, 1), (...","[(May, 3196), (Nov, 2998), (Mar, 1907), (Dec, ...","[(2, 6601), (1, 2585), (3, 2555), (4, 478), (8...","[(2.0, 7835), (1.0, 2424), (4.0, 725), (5.0, 4...","[(1.0, 4695), (3.0, 2345), (4.0, 1157), (2.0, ...","[(2, 3913), (1, 2451), (3, 2052), (4, 1069), (...","[(Returning_Visitor, 10551), (New_Visitor, 169...","[(False, 9273), (True, 2868), (Name:Zara, 189)]","[(False, 10303), (True, 1880), (nan, 147)]"
top_value,"(12329, 1)","(May, 3196)","(2, 6601)","(2.0, 7835)","(1.0, 4695)","(2, 3913)","(Returning_Visitor, 10551)","(False, 9273)","(False, 10303)"
bottom_value,"(10, 1)","(Sept, 89)","(5, 6)","(9.0, 1)","(nan, 246)","(17, 1)","(Other, 85)","(Name:Zara, 189)","(nan, 147)"

[                   Administrative Administrative_Duration Informational  \
 data_type                   int64                 float64         int64
 max_value                      27                989493.0            24
 min_value                     -10                     0.0             0
 mean_value                 2.2382             1269.776004      0.503569
 standard_deviation       3.409269             34071.46693      1.270156

                    Informational_Duration ProductRelated  \
 data_type                         float64          int64
 max_value                        2549.375            705
 min_value                             0.0              0
 mean_value                      34.472398      31.731468
 standard_deviation             140.749294      44.475503

                    ProductRelated_Duration
 data_type                          float64
 max_value                      63973.52223
 min_value                              0.0
 mean_value                      1194.74622
 standard_deviation             1913.669288  ,
                    BounceRates ExitRates  PageValues
 data_type              float64   float64     float64
 max_value             2.098952       0.2  361.763742
 min_value             -0.49868       0.0         0.0
 mean_value            0.044239  0.043073    5.889258
 standard_deviation    0.239735  0.048597   18.568437,
                    SpecialDay
 data_type             float64
 max_value                 1.0
 min_value                 0.0
 mean_value            0.06126
 standard_deviation    0.19865,
                                                       Unnamed: 0  \
 data_type                                                  int64
 unique_values  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
 value_counts   [(12329, 1), (0, 1), (1, 1), (2, 1), (3, 1), (...
 top_value                                             (12329, 1)
 bottom_value                                             (10, 1)

                                                            Month  \
 data_type                                                 object
 unique_values  [Feb, Mar, May, Turc, Oct, June, Jul, Aug, Nov...
 value_counts   [(May, 3196), (Nov, 2998), (Mar, 1907), (Dec, ...
 top_value                                            (May, 3196)
 bottom_value                                          (Sept, 89)

                                                 OperatingSystems  \
 data_type                                                  int64
 unique_values                           [1, 2, 4, 3, 7, 6, 8, 5]
 value_counts   [(2, 6601), (1, 2585), (3, 2555), (4, 478), (8...
 top_value                                              (2, 6601)
 bottom_value                                              (5, 6)

                                                          Browser  \
 data_type                                                float64
 unique_values  [nan, 2.0, 1.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0,...
 value_counts   [(2.0, 7835), (1.0, 2424), (4.0, 725), (5.0, 4...
 top_value                                            (2.0, 7835)
 bottom_value                                            (9.0, 1)

                                                           Region  \
 data_type                                                float64
 unique_values  [1.0, nan, 2.0, 3.0, 4.0, 9.0, 5.0, 6.0, 7.0, ...
 value_counts   [(1.0, 4695), (3.0, 2345), (4.0, 1157), (2.0, ...
 top_value                                            (1.0, 4695)
 bottom_value                                          (nan, 246)

                                                      TrafficType  \
 data_type                                                  int64
 unique_values  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
 value_counts   [(2, 3913), (1, 2451), (3, 2052), (4, 1069), (...
 top_value                                              (2, 3913)
 bottom_value                                             (17, 1)

                                                      VisitorType  \
 data_type                                                 object
 unique_values            [Returning_Visitor, New_Visitor, Other]
 value_counts   [(Returning_Visitor, 10551), (New_Visitor, 169...
 top_value                             (Returning_Visitor, 10551)
 bottom_value                                         (Other, 85)

                                                        Weekend  \
 data_type                                               object
 unique_values                         [False, True, Name:Zara]
 value_counts   [(False, 9273), (True, 2868), (Name:Zara, 189)]
 top_value                                        (False, 9273)
 bottom_value                                  (Name:Zara, 189)

                                                   Revenue
 data_type                                          object
 unique_values                          [False, nan, True]
 value_counts   [(False, 10303), (True, 1880), (nan, 147)]
 top_value                                  (False, 10303)
 bottom_value                                   (nan, 147)  ]

In [ ]:
def analyze_negative_values(df, column_name, target_column='Revenue'):
    """
    Analyze rows with negative values in a specified column.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe to analyze
    column_name : str
        The column to check for negative values
    target_column : str, default='Revenue'
        The target column to analyze conversion rates
        
    Returns:
    --------
    tuple
        (df with negative values, df with positive values, row indices to remove)
    """
    # Create filter for negative values
    neg_values_filter = df[column_name] < 0
    
    # Get dataframes with negative and positive values
    neg_values_df = df[neg_values_filter]
    pos_values_df = df[~neg_values_filter]
    
    # Print basic statistics
    total_rows = len(df)
    neg_rows = len(neg_values_df)
    neg_pct = round(neg_rows / total_rows, 4)
    
    print(f"Found {neg_rows} rows with negative values in {column_name} ({neg_pct * 100}% of all data)")
    
    # Check target column distribution if it exists
    if target_column in df.columns:
        target_total = len(df[df[target_column] == True])
        target_neg = len(neg_values_df[neg_values_df[target_column] == True])
        target_pct = round(target_neg / target_total, 4)
        
        print(f"Of these, {target_neg} are conversions ({target_pct * 100}% of all conversions)")
    
    # Summarize the negative value rows
    print("\nSummary of rows with negative values:")
    summarise_df(neg_values_df)
    
    # If numeric column, compare metrics
    if pd.api.types.is_numeric_dtype(df[column_name]):
        # Create "per-unit" measures if applicable
        # This is specific to each column and would need customization
        
        if column_name.endswith('_Duration'):
            # For duration columns, calculate duration per page view
            base_col = column_name.replace('_Duration', '')
            
            # For positive values
            pos_values_df['Per unit metric'] = pos_values_df[column_name] / pos_values_df[base_col].replace(0, np.nan)
            pos_mean = round(pos_values_df['Per unit metric'].mean(), 4)
            
            # For negative values - make them positive for calculation
            temp_neg_df = neg_values_df.copy()
            temp_neg_df[column_name] = temp_neg_df[column_name].abs()
            temp_neg_df['Per unit metric'] = temp_neg_df[column_name] / temp_neg_df[base_col].replace(0, np.nan)
            neg_mean = round(temp_neg_df['Per unit metric'].mean(), 4)
            
            print(f"\nMean {column_name} per {base_col}:")
            print(f"- Positive rows: {pos_mean}")
            print(f"- Negative rows (absolute): {neg_mean}")
            print(f"- Ratio: {round(pos_mean / neg_mean, 4)}")
        else:
            # For other numeric columns, just compare basic stats
            pos_mean = round(pos_values_df[column_name].mean(), 4)
            neg_mean_abs = round(neg_values_df[column_name].abs().mean(), 4)
            
            print(f"\nMean {column_name}:")
            print(f"- Positive rows: {pos_mean}")
            print(f"- Negative rows (absolute): {neg_mean_abs}")
    
    # Get indices of negative rows for potential removal
    rows_with_neg_values_ids = neg_values_df.index
    
    return neg_values_df, pos_values_df, rows_with_neg_values_ids

In [81]:
column_info_page_views_and_duration_list = ['Administrative', 'Administrative_Duration', 'Informational','Informational_Duration', 'ProductRelated','ProductRelated_Duration']
column_info_google_analytics_list = ['BounceRates','ExitRates','PageValues']
column_info_time_categories_list = ['SpecialDay', 'Month', 'Weekend']
column_info_misc_categories_list = ['OperatingSystems','Browser','Region','TrafficType','VisitorType']

In [ ]:
analyze_negative_values(session_data_df, 'Administrative')

In [ ]:
sns.boxplot(data=session_data_df, x='Revenue', y='Administrative')

In [82]:
test_dict = {'A' : {'Value': 2, 'Value': 4}, "B" : {'Value': 3, 'Value': 6}}

In [83]:
pd.DataFrame(test_dict)

       A  B
Value  4  6

In [84]:
test_dict = {'A' : [None, 4, -6], "B" : [4, None, 9]}

In [85]:
test_dict_df = pd.DataFrame(test_dict)

test_dict_df

     A    B
0  NaN  4.0
1  4.0  NaN
2 -6.0  9.0

In [86]:
test_dict_df.loc[test_dict_df['A'] < 0, 'A'] = test_dict_df.loc[test_dict_df['A'] < 0, 'A'] * -1

In [87]:
test_dict_df

     A    B
0  NaN  4.0
1  4.0  NaN
2  6.0  9.0

In [88]:
fill_nans_with = {'A' : 0, 'B' : 'Unknown'}

In [89]:
test_dict_df.fillna(fill_nans_with)

     A        B
0  0.0      4.0
1  4.0  Unknown
2  6.0      9.0

In [90]:
test_dict_df

     A    B
0  NaN  4.0
1  4.0  NaN
2  6.0  9.0

In [91]:
test_dict_df.drop(test_dict_df[test_dict_df['A'] == 4].index, axis=0, inplace=True)

In [92]:
test_dict_df

     A    B
0  NaN  4.0
2  6.0  9.0

In [93]:
outliers_to_drop_from_administrative_duration = session_data_df['Administrative_Duration'].nlargest(15).index

session_data_df.drop(index=outliers_to_drop_from_administrative_duration, inplace=True)

display(session_data_df['Administrative_Duration'].nlargest(20))

8071     3398.750000
5776     2720.500000
9238     2657.318056
5152     2629.253968
6165     2407.423810
4884     2156.166667
11712    2137.112745
9736     2086.750000
1572     2047.234848
4509     1951.279141
9662     1946.000000
12017    1922.000000
3654     1764.000000
3227     1751.047619
8707     1715.000000
2446     1687.500000
5754     1672.033333
9633     1668.500000
6645     1660.300000
8368     1652.000000
Name: Administrative_Duration, dtype: float64

In [ ]:
test_dict_df.dropna(subset='A')

In [ ]:
test_dict_df[test_dict_df['A'] == 2]

In [ ]:
# Dictionary with all the columns + description of each. The decription in the dict is my interpretation of the source
# documentation which was sparse on column descriptions.
column_descriptions = {
    "Administrative": {
        "description": "Number of page visits within this category",
        "type": "numeric",
        "data_type": "int64"
    },
    "Administrative_Duration": {
        "description": "Time spent within this category",
        "type": "numeric",
        "data_type": "float64"
    },
    "Informational": {
        "description": "Number of page visits within this category",
        "type": "numeric",
        "data_type": "int64"
    },
    "Informational_Duration": {
        "description": "Time spent within this category",
        "type": "numeric",
        "data_type": "float64"
    },
    "ProductRelated": {
        "description": "Number of page visits within this category",
        "type": "numeric",
        "data_type": "int64"
    },
    "ProductRelated_Duration": {
        "description": "Time spent within this category",
        "type": "numeric",
        "data_type": "float64"
    },
    "BounceRates": {
        "description": "Bounce rate of current page",
        "type": "numeric",
        "data_type": "float64"
    },
    "ExitRates": {
        "description": "Exit rate value of current page",
        "type": "numeric",
        "data_type": "float64"
    },
    "PageValues": {
        "description": "Page value of current page",
        "type": "numeric",
        "data_type": "float64"
    },
    "SpecialDay": {
        "description": "Proximity in time of the session to a special day (e.g. Mother's Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina's day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8.",
        "type": "numeric",
        "data_type": "float64"
    },
    "Month": {
        "description": "Month of session",
        "type": "categorical",
        "data_type": "object"
    },
    "Weekend": {
        "description": "Boolean if the session day was in the weekend",
        "type": "categorical",
        "data_type": "object" 
    },
    "OperatingSystems": {
        "description": "Different OS' represented by different integers",
        "type": "categorical",  
        "data_type": "int64"
    },
    "Browser": {
        "description": "Different browsers represented by different integers",
        "type": "categorical",  
        "data_type": "float64" 
    },
    "Region": {
        "description": "Different regions represented by different integers",
        "type": "categorical", 
        "data_type": "float64"  
    },
    "TrafficType": {
        "description": "Different traffic types represented by different integers",
        "type": "categorical",  
        "data_type": "int64"
    },
    "VisitorType": {
        "description": "Different visitor types represented by different categorical values",
        "type": "categorical",
        "data_type": "object"
    },
    "Revenue": {
        "description": "Whether revenue was generated during this session (target variable)",
        "type": "categorical",
        "data_type": "object" 
    }
}

# Lists grouping together columns of similar kind.
column_info_page_views_and_duration_list = ['Administrative', 'Administrative_Duration', 'Informational','Informational_Duration', 'ProductRelated','ProductRelated_Duration']
column_info_google_analytics_list = ['BounceRates','ExitRates','PageValues']
column_info_time_categories_list = ['SpecialDay', 'Month', 'Weekend']
column_info_misc_categories_list = ['OperatingSystems','Browser','Region','TrafficType','VisitorType']

In [ ]:
def plot_feature_eda(df, column_descriptions, figsize=(16, 5), revenue_col='Revenue', n_cols=2):
    """
    Generates lightweight exploratory data analysis plots for each feature in the dataset.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 5))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
    n_cols : int, optional (default=2)
        Number of columns in the subplot grid
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    
    # Extract feature types from column_descriptions
    numeric_features = []
    categorical_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info["type"] == "numeric":
                numeric_features.append(col)
            else:
                categorical_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in info:
                numeric_features.append(col)
            else:
                categorical_features.append(col)
    
    # Function to create plots for numeric features
    def plot_numeric_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Simple histogram with mean and median lines
        sns.histplot(df[feature].dropna(), bins=30, kde=False, ax=axes[0])
        
        # Add mean line (red dotted)
        mean_val = df[feature].mean()
        axes[0].axvline(mean_val, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Mean: {mean_val:.2f}')
        
        # Add median line (green dotted) - using same style as mean line
        median_val = df[feature].median()
        axes[0].axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                       label=f'Median: {median_val:.2f}')
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Distribution of {feature}')
        axes[0].set_xlabel(feature)
        
        # Right plot: Box plot by Revenue with mean and median annotations
        sns.boxplot(x=revenue_col, y=feature, data=df, ax=axes[1])
        
        # Add mean and median for each group on the right side of each bar
        for i, rev_val in enumerate([False, True]):
            group_data = df[df[revenue_col] == rev_val][feature].dropna()
            
            if len(group_data) > 0:
                group_mean = group_data.mean()
                group_median = group_data.median()
                
                # Get y-axis limits to position annotations
                ymin, ymax = axes[1].get_ylim()
                # Position at the middle of the box
                annotation_y = group_median
                
                # Get x position (slightly to the right of the box)
                box_width = 0.4  # Default box width in seaborn
                annotation_x = i + box_width/2 + 0.1
                
                # Create box with mean and median on the right side
                axes[1].text(annotation_x, annotation_y, 
                           f"mean: {group_mean:.2f}\nmedian: {group_median:.2f}", 
                           ha='left', va='center',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'),
                           color='black')
                
                # Add individual mean and median lines with colors
                mean_text = f"mean: {group_mean:.2f}"
                median_text = f"median: {group_median:.2f}"
                
                # Split the text to color each part
                axes[1].text(annotation_x, annotation_y + (ymax-ymin)*0.02, 
                           mean_text, 
                           ha='left', va='center', color='red',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'))
                
                axes[1].text(annotation_x, annotation_y - (ymax-ymin)*0.02, 
                           median_text, 
                           ha='left', va='center', color='green',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'))
                
        axes[1].set_title(f'{feature} by {revenue_col}')
            
        plt.tight_layout()
        plt.show()
    
    # Function to create plots for categorical features
    def plot_categorical_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Count plot with all categories
        order = df[feature].value_counts().index
        sns.countplot(y=feature, data=df, order=order, ax=axes[0])
        axes[0].set_title(f'Count of {feature}')
        axes[0].set_ylabel(feature)
        
        # Right plot: Stacked bar chart by Revenue showing comparison to overall conversion rate
        crosstab = pd.crosstab(df[feature], df[revenue_col], normalize='index')
        
        # Simplified handling - just use the boolean values directly
        # Create the plot with colors
        colors = {True: 'gold', False: 'steelblue'}
        try:
            # Try to put True first if it exists
            if True in crosstab.columns:
                ordered_columns = [True, False]
                ordered_columns = [col for col in ordered_columns if col in crosstab.columns]
                crosstab = crosstab[ordered_columns]
            
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], 
                         color=[colors.get(col, 'gray') for col in crosstab.columns])
        except:
            # Fallback if something goes wrong
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        
        # Calculate overall proportion of True in the dataset
        overall_true_proportion = df[revenue_col].mean()
        
        # Add a reference line for the overall proportion at 0.85 instead of 0.15
        # This makes it easier to compare with the True portion
        axes[1].axvline(x=0.85, color='red', linestyle='--', linewidth=1.5,
                        label=f'Overall True: {overall_true_proportion:.2f}')
        
        axes[1].legend(loc='lower right')
        axes[1].set_title(f'Conversion Rate by {feature} vs. Overall Rate')
        axes[1].set_xlabel('Proportion')
        axes[1].set_ylabel(feature)
        
        plt.tight_layout()
        plt.show()
    
    # Function to show basic stats before plotting
    def plot_feature(feature):
        print(f"\n{'='*40}")
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature]["description"]
        else:
            desc = column_descriptions[feature].split("Type:")[0].strip()
            
        print(f"Feature: {feature}")
        print(f"Description: {desc}")
        print(f"Missing Values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        
        if feature in numeric_features:
            # Print only basic summary statistics
            stats_df = pd.DataFrame({
                'Min': df[feature].min(),
                'Max': df[feature].max(),
                'Mean': df[feature].mean(),
                'Median': df[feature].median()
            }, index=[0])
            print("\nBasic Statistics:")
            print(stats_df.to_string(index=False))
            
            plot_numeric_feature(feature)
        else:
            # Print only top categories
            value_counts = df[feature].value_counts()
            print("\nTop 5 Categories:")
            print(value_counts.head(5).to_string())
            
            plot_categorical_feature(feature)
    
    # Plot each feature
    for feature in numeric_features + categorical_features:
        plot_feature(feature)

In [ ]:
plot_feature_eda(session_data_df, column_descriptions)

In [ ]:
def plot_numeric_features_log(df, column_descriptions, figsize=(16, 6), revenue_col='Revenue'):
    """
    Generates exploratory data analysis plots for numeric features using log transformations 
    and scatter plots to better visualize data with wide ranges.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 6))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    import numpy as np
    
    # Extract numeric features from column_descriptions
    numeric_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info.get("type") == "numeric":
                numeric_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in str(info):
                numeric_features.append(col)
    
    # Function to plot a single numeric feature
    def plot_single_feature(feature):
        fig, axes = plt.subplots(1, 2, figsize=figsize)
        
        # Skip if all values are 0 (log would be meaningless)
        if df[feature].max() == 0:
            print(f"Skipping {feature} - all values are 0")
            plt.close(fig)
            return
        
        # For features with zeros, use log1p transformation
        has_zeros = (df[feature].min() == 0)
        
        if has_zeros:
            log_data = np.log1p(df[feature].dropna())
            log_function = np.log1p
            inverse_function = np.expm1
            log_label = f'log(1+{feature})'
        else:
            log_data = np.log(df[feature].dropna())
            log_function = np.log
            inverse_function = np.exp
            log_label = f'log({feature})'
        
        # Left plot: Histogram with log transformation
        sns.histplot(log_data, bins=30, kde=True, ax=axes[0])
        
        # Add mean and median lines on the log-transformed scale
        log_mean = log_data.mean()
        log_median = log_data.median()
        
        axes[0].axvline(log_mean, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Log Mean: {log_mean:.2f}')
        axes[0].axvline(log_median, color='green', linestyle='--', linewidth=1.5,
                       label=f'Log Median: {log_median:.2f}')
        
        # Add original scale values for key percentiles
        percentiles = [5, 25, 50, 75, 95]
        log_percentiles = np.percentile(log_data, percentiles)
        
        for i, p in enumerate(percentiles):
            if i % 2 == 0:  # Only annotate alternate percentiles to avoid crowding
                val = log_percentiles[i]
                original_val = inverse_function(val)
                axes[0].axvline(val, color='gray', linestyle=':', alpha=0.7)
                axes[0].text(val, 0.8 * axes[0].get_ylim()[1], 
                            f'{p}%: {original_val:.1f}', 
                            rotation=90, ha='center', fontsize=8)
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Log-Transformed Distribution of {feature}')
        axes[0].set_xlabel(log_label)
        
        # Right plot: Scatter plot by Revenue
        # Create jittered x positions
        df_valid = df.dropna(subset=[feature, revenue_col])
        
        revenue_values = df_valid[revenue_col].astype(bool)  # Ensure boolean type
        x_jitter = np.random.normal(0, 0.05, size=len(df_valid))
        x_positions = revenue_values.map({False: 0, True: 1}).values + x_jitter
        
        # Apply log transformation to feature values
        y_values = log_function(df_valid[feature].values.astype(float))
        
        # Plot with transparency to handle overlapping points
        scatter = axes[1].scatter(x_positions, y_values, 
                                alpha=0.4, s=20, c='blue', edgecolor='none')
        
        # Add mean and median indicators for each group
        for i, rev_val in enumerate([False, True]):
            group_data = df_valid[df_valid[revenue_col] == rev_val][feature]
            
            if len(group_data) > 0:
                group_log_mean = log_function(group_data.mean())
                group_log_median = log_function(group_data.median())
                
                # Plot horizontal lines for mean and median
                axes[1].plot([i-0.2, i+0.2], [group_log_mean, group_log_mean], 'r-', linewidth=2, 
                            label=f'Mean (log)' if i == 0 else "")
                axes[1].plot([i-0.2, i+0.2], [group_log_median, group_log_median], 'g-', linewidth=2,
                            label=f'Median (log)' if i == 0 else "")
                
                # Add text labels with original scale values
                axes[1].text(i+0.25, group_log_mean, 
                            f'Mean: {group_data.mean():.1f}', 
                            color='red', ha='left', va='center')
                axes[1].text(i+0.25, group_log_median, 
                            f'Median: {group_data.median():.1f}', 
                            color='green', ha='left', va='center')
        
        # Set x-axis labels
        axes[1].set_xticks([0, 1])
        axes[1].set_xticklabels(['False', 'True'])
        axes[1].set_xlabel(revenue_col)
        axes[1].set_ylabel(log_label)
        axes[1].set_title(f'Log-Transformed {feature} by {revenue_col}')
        axes[1].legend(loc='best')
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature].get("description", "")
        else:
            desc = str(column_descriptions[feature]).split("Type:")[0].strip()
        
        plt.suptitle(f"{feature}: {desc}", fontsize=12)
        plt.tight_layout(rect=[0, 0, 1, 0.96])  # Make room for suptitle
        plt.show()
        
        # Print basic statistics for the feature
        stats = df[feature].describe(percentiles=[.05, .25, .5, .75, .95])
        print(f"\nStatistics for {feature}:")
        print(stats)
        print(f"Missing values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        print("-" * 50)
    
    # Process each numeric feature
    for feature in numeric_features:
        print(f"\nAnalyzing: {feature}")
        try:
            plot_single_feature(feature)
        except Exception as e:
            print(f"Error plotting {feature}: {e}")

In [ ]:
plot_numeric_features_log(session_data_df, column_descriptions)

In [ ]:
def plot_feature_eda(df, column_descriptions, figsize=(16, 5), revenue_col='Revenue', n_cols=2):
    """
    Generates lightweight exploratory data analysis plots for each feature in the dataset.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 5))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
    n_cols : int, optional (default=2)
        Number of columns in the subplot grid
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    
    # Extract feature types from column_descriptions
    numeric_features = []
    categorical_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info["type"] == "numeric":
                numeric_features.append(col)
            else:
                categorical_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in info:
                numeric_features.append(col)
            else:
                categorical_features.append(col)
    
    # Function to create plots for numeric features
    def plot_numeric_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Simple histogram with mean and median lines
        sns.histplot(df[feature].dropna(), bins=30, kde=False, ax=axes[0])
        
        # Add mean line (red dotted)
        mean_val = df[feature].mean()
        axes[0].axvline(mean_val, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Mean: {mean_val:.2f}')
        
        # Add median line (green dotted) - using same style as mean line
        median_val = df[feature].median()
        axes[0].axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                       label=f'Median: {median_val:.2f}')
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Distribution of {feature}')
        axes[0].set_xlabel(feature)
        
        # Right plot: Box plot by Revenue with mean and median annotations at the top
        sns.boxplot(x=revenue_col, y=feature, data=df, ax=axes[1])
        
        # Add mean and median for each group at the top of the chart
        for i, rev_val in enumerate([False, True]):
            group_data = df[df[revenue_col] == rev_val][feature].dropna()
            
            if len(group_data) > 0:
                group_mean = group_data.mean()
                group_median = group_data.median()
                
                # Get y-axis limits to position annotations at the top
                ymin, ymax = axes[1].get_ylim()
                annotation_y = ymax - (ymax - ymin) * 0.05
                
                # Create combined annotation at the top
                axes[1].text(i, annotation_y, 
                           f"μ: {group_mean:.2f}\nm: {group_median:.2f}", 
                           ha='center', va='top', fontweight='bold',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'))
                
        axes[1].set_title(f'{feature} by {revenue_col}')
            
        plt.tight_layout()
        plt.show()
    
    # Function to create plots for categorical features
    def plot_categorical_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Count plot with all categories
        order = df[feature].value_counts().index
        sns.countplot(y=feature, data=df, order=order, ax=axes[0])
        axes[0].set_title(f'Count of {feature}')
        axes[0].set_ylabel(feature)
        
        # Right plot: Stacked bar chart by Revenue showing comparison to overall conversion rate
        crosstab = pd.crosstab(df[feature], df[revenue_col], normalize='index')
        
        # Make sure True is always on the left side
        # First, identify which column corresponds to True (could be True or 'True')
        true_column = None
        if True in crosstab.columns:
            true_column = True
        elif 'True' in crosstab.columns:
            true_column = 'True'
            
        # Create custom color dictionary to ensure True always has the same color
        colors = {'True': 'gold', True: 'gold', 'False': 'steelblue', False: 'steelblue'}
        
        # Create the plot, with True first if possible
        if true_column is not None:
            # First create a new dataframe with columns in the order we want
            false_column = False if isinstance(true_column, bool) else 'False'
            columns_to_use = [col for col in crosstab.columns if col not in [true_column, false_column]]
            new_order = [true_column, false_column] + columns_to_use
            
            # Try to reorder - use only columns that exist
            available_columns = [col for col in new_order if col in crosstab.columns]
            try:
                ordered_crosstab = crosstab[available_columns]
                ordered_crosstab.plot(kind='barh', stacked=True, ax=axes[1], color=[colors.get(col, None) for col in available_columns])
            except:
                # Fallback if reordering fails
                crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        else:
            # If we can't identify True column, just use the original dataframe
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        
        # Calculate overall proportion of True/False in the dataset
        overall_true_proportion = df[revenue_col].mean() if df[revenue_col].dtype == bool else df[revenue_col].eq(True).mean()
        
        # Add a reference line for the overall proportion - now on the left side
        axes[1].axvline(x=overall_true_proportion, color='red', linestyle='--', linewidth=1.5,
                        label=f'Overall True: {overall_true_proportion:.2f}')
        
        axes[1].legend(loc='lower right')
        axes[1].set_title(f'Conversion Rate by {feature} vs. Overall Rate')
        axes[1].set_xlabel('Proportion')
        axes[1].set_ylabel(feature)
        
        plt.tight_layout()
        plt.show()
    
    # Function to show basic stats before plotting
    def plot_feature(feature):
        print(f"\n{'='*40}")
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature]["description"]
        else:
            desc = column_descriptions[feature].split("Type:")[0].strip()
            
        print(f"Feature: {feature}")
        print(f"Description: {desc}")
        print(f"Missing Values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        
        if feature in numeric_features:
            # Print only basic summary statistics
            stats_df = pd.DataFrame({
                'Min': df[feature].min(),
                'Max': df[feature].max(),
                'Mean': df[feature].mean(),
                'Median': df[feature].median()
            }, index=[0])
            print("\nBasic Statistics:")
            print(stats_df.to_string(index=False))
            
            plot_numeric_feature(feature)
        else:
            # Print only top categories
            value_counts = df[feature].value_counts()
            print("\nTop 5 Categories:")
            print(value_counts.head(5).to_string())
            
            plot_categorical_feature(feature)
    
    # Plot each feature
    for feature in numeric_features + categorical_features:
        plot_feature(feature)

In [ ]:
plot_feature_eda(session_data_df, column_descriptions)

In [ ]:
def plot_feature_eda(df, column_descriptions, figsize=(16, 5), revenue_col='Revenue', n_cols=2):
    """
    Generates lightweight exploratory data analysis plots for each feature in the dataset.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 5))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
    n_cols : int, optional (default=2)
        Number of columns in the subplot grid
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    
    # Extract feature types from column_descriptions
    numeric_features = []
    categorical_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info["type"] == "numeric":
                numeric_features.append(col)
            else:
                categorical_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in info:
                numeric_features.append(col)
            else:
                categorical_features.append(col)
    
    # Function to create plots for numeric features
    def plot_numeric_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Simple histogram with mean and median lines
        sns.histplot(df[feature].dropna(), bins=30, kde=False, ax=axes[0])
        
        # Add mean line (red dotted)
        mean_val = df[feature].mean()
        axes[0].axvline(mean_val, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Mean: {mean_val:.2f}')
        
        # Add median line (green dotted) - using same style as mean line
        median_val = df[feature].median()
        axes[0].axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                       label=f'Median: {median_val:.2f}')
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Distribution of {feature}')
        axes[0].set_xlabel(feature)
        
        # Right plot: Box plot by Revenue with mean and median annotations
        sns.boxplot(x=revenue_col, y=feature, data=df, ax=axes[1])
        
        # Add mean and median for each group on the right side of each bar
        for i, rev_val in enumerate([False, True]):
            group_data = df[df[revenue_col] == rev_val][feature].dropna()
            
            if len(group_data) > 0:
                group_mean = group_data.mean()
                group_median = group_data.median()
                
                # Get y-axis limits to position annotations
                ymin, ymax = axes[1].get_ylim()
                # Position at the middle of the box
                annotation_y = group_median
                
                # Get x position (slightly to the right of the box)
                box_width = 0.4  # Default box width in seaborn
                annotation_x = i + box_width/2 + 0.1
                
                # Create box with mean and median on the right side
                axes[1].text(annotation_x, annotation_y, 
                           f"mean: {group_mean:.2f}\nmedian: {group_median:.2f}", 
                           ha='left', va='center',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'),
                           color='black')
                
                # Add individual mean and median lines with colors
                mean_text = f"mean: {group_mean:.2f}"
                median_text = f"median: {group_median:.2f}"
                
                # Split the text to color each part
                axes[1].text(annotation_x, annotation_y + (ymax-ymin)*0.02, 
                           mean_text, 
                           ha='left', va='center', color='red',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'))
                
                axes[1].text(annotation_x, annotation_y - (ymax-ymin)*0.02, 
                           median_text, 
                           ha='left', va='center', color='green',
                           bbox=dict(facecolor='white', alpha=0.7, boxstyle='round,pad=0.3'))
                
        axes[1].set_title(f'{feature} by {revenue_col}')
            
        plt.tight_layout()
        plt.show()
    
    # Function to create plots for categorical features
    def plot_categorical_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Count plot with all categories
        order = df[feature].value_counts().index
        sns.countplot(y=feature, data=df, order=order, ax=axes[0])
        axes[0].set_title(f'Count of {feature}')
        axes[0].set_ylabel(feature)
        
        # Right plot: Stacked bar chart by Revenue showing comparison to overall conversion rate
        crosstab = pd.crosstab(df[feature], df[revenue_col], normalize='index')
        
        # Simplified handling - just use the boolean values directly
        # Create the plot with colors
        colors = {True: 'gold', False: 'steelblue'}
        try:
            # Try to put True first if it exists
            if True in crosstab.columns:
                ordered_columns = [True, False]
                ordered_columns = [col for col in ordered_columns if col in crosstab.columns]
                crosstab = crosstab[ordered_columns]
            
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], 
                         color=[colors.get(col, 'gray') for col in crosstab.columns])
        except:
            # Fallback if something goes wrong
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        
        # Calculate overall proportion of True in the dataset
        overall_true_proportion = df[revenue_col].mean()
        
        # Add a reference line for the overall proportion at 0.85 instead of 0.15
        # This makes it easier to compare with the True portion
        axes[1].axvline(x=0.85, color='red', linestyle='--', linewidth=1.5,
                        label=f'Overall True: {overall_true_proportion:.2f}')
        
        axes[1].legend(loc='lower right')
        axes[1].set_title(f'Conversion Rate by {feature} vs. Overall Rate')
        axes[1].set_xlabel('Proportion')
        axes[1].set_ylabel(feature)
        
        plt.tight_layout()
        plt.show()
    
    # Function to show basic stats before plotting
    def plot_feature(feature):
        print(f"\n{'='*40}")
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature]["description"]
        else:
            desc = column_descriptions[feature].split("Type:")[0].strip()
            
        print(f"Feature: {feature}")
        print(f"Description: {desc}")
        print(f"Missing Values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        
        if feature in numeric_features:
            # Get the values for statistics
            min_val = df[feature].min()
            max_val = df[feature].max()
            mean_val = df[feature].mean()
            median_val = df[feature].median()
            
            # Print statistics with the requested format
            print("Basic Statistics:")
            print(f" Min      Max        Mean  Median")
            print(f" {min_val} {max_val} {mean_val} {median_val}")
            
            plot_numeric_feature(feature)
        else:
            # Print only top categories
            value_counts = df[feature].value_counts()
            print("\nTop 5 Categories:")
            print(value_counts.head(5).to_string())
            
            plot_categorical_feature(feature)
    
    # Plot each feature
    for feature in numeric_features + categorical_features:
        plot_feature(feature)

In [ ]:
plot_feature_eda(session_data_df, column_descriptions)

In [ ]:
def plot_feature_eda(df, column_descriptions, figsize=(16, 5), revenue_col='Revenue', n_cols=2):
    """
    Generates lightweight exploratory data analysis plots for each feature in the dataset.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 5))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
    n_cols : int, optional (default=2)
        Number of columns in the subplot grid
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    
    # Extract feature types from column_descriptions
    numeric_features = []
    categorical_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info["type"] == "numeric":
                numeric_features.append(col)
            else:
                categorical_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in info:
                numeric_features.append(col)
            else:
                categorical_features.append(col)
    
    # Function to create plots for numeric features
    def plot_numeric_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Simple histogram with mean and median lines
        sns.histplot(df[feature].dropna(), bins=30, kde=False, ax=axes[0])
        
        # Add mean line (red dotted)
        mean_val = df[feature].mean()
        axes[0].axvline(mean_val, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Mean: {mean_val:.2f}')
        
        # Add median line (green dotted) - using same style as mean line
        median_val = df[feature].median()
        axes[0].axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                       label=f'Median: {median_val:.2f}')
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Distribution of {feature}')
        axes[0].set_xlabel(feature)
        
        # Right plot: Box plot by Revenue with mean and median annotations
        sns.boxplot(x=revenue_col, y=feature, data=df, ax=axes[1])
        
        # Add mean and median for each group in a single box at the top right of each bar
        for i, rev_val in enumerate([False, True]):
            group_data = df[df[revenue_col] == rev_val][feature].dropna()
            
            if len(group_data) > 0:
                group_mean = group_data.mean()
                group_median = group_data.median()
                
                # Get y-axis limits to position annotations
                ymin, ymax = axes[1].get_ylim()
                
                # Position at the top right of each box
                box_width = 0.4  # Default box width in seaborn
                annotation_x = i + box_width/2 + 0.1
                annotation_y = ymax - (ymax - ymin) * 0.1  # Position near the top
                
                # Create a single box with both mean and median
                # Use the respective colors for mean and median values
                annotation_text = f"mean: {group_mean:.2f}\nmedian: {group_median:.2f}"
                
                # Add the combined annotation box
                axes[1].text(
                    annotation_x, annotation_y,
                    annotation_text,
                    ha='left', va='top',
                    bbox=dict(facecolor='white', alpha=0.85, boxstyle='round,pad=0.3', edgecolor='gray'),
                    color='black'
                )
                
        axes[1].set_title(f'{feature} by {revenue_col}')
            
        plt.tight_layout()
        plt.show()
    
    # Function to create plots for categorical features
    def plot_categorical_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Count plot with all categories
        order = df[feature].value_counts().index
        sns.countplot(y=feature, data=df, order=order, ax=axes[0])
        axes[0].set_title(f'Count of {feature}')
        axes[0].set_ylabel(feature)
        
        # Right plot: Stacked bar chart by Revenue showing comparison to overall conversion rate
        crosstab = pd.crosstab(df[feature], df[revenue_col], normalize='index')
        
        # Simplified handling - just use the boolean values directly
        # Create the plot with colors
        colors = {True: 'gold', False: 'steelblue'}
        try:
            # Try to put True first if it exists
            if True in crosstab.columns:
                ordered_columns = [True, False]
                ordered_columns = [col for col in ordered_columns if col in crosstab.columns]
                crosstab = crosstab[ordered_columns]
            
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], 
                         color=[colors.get(col, 'gray') for col in crosstab.columns])
        except:
            # Fallback if something goes wrong
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        
        # Calculate overall proportion of True in the dataset
        overall_true_proportion = df[revenue_col].mean()
        
        # Add a reference line for the overall proportion at 0.85 instead of 0.15
        # This makes it easier to compare with the True portion
        axes[1].axvline(x=0.85, color='red', linestyle='--', linewidth=1.5,
                        label=f'Overall True: {overall_true_proportion:.2f}')
        
        axes[1].legend(loc='lower right')
        axes[1].set_title(f'Conversion Rate by {feature} vs. Overall Rate')
        axes[1].set_xlabel('Proportion')
        axes[1].set_ylabel(feature)
        
        plt.tight_layout()
        plt.show()
    
    # Function to show basic stats before plotting
    def plot_feature(feature):
        print(f"\n{'='*40}")
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature]["description"]
        else:
            desc = column_descriptions[feature].split("Type:")[0].strip()
            
        print(f"Feature: {feature}")
        print(f"Description: {desc}")
        print(f"Missing Values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        
        if feature in numeric_features:
            # Get the values for statistics
            min_val = df[feature].min()
            max_val = df[feature].max()
            mean_val = df[feature].mean()
            median_val = df[feature].median()
            
            # Print statistics with the requested format
            print("Basic Statistics:")
            print(f" Min      Max        Mean  Median")
            print(f" {min_val} {max_val} {mean_val} {median_val}")
            
            plot_numeric_feature(feature)
        else:
            # Print only top categories
            value_counts = df[feature].value_counts()
            print("\nTop 5 Categories:")
            print(value_counts.head(5).to_string())
            
            plot_categorical_feature(feature)
    
    # Plot each feature
    for feature in numeric_features + categorical_features:
        plot_feature(feature)

In [ ]:
plot_feature_eda(session_data_df, column_descriptions)

In [ ]:
def plot_feature_eda(df, column_descriptions, figsize=(16, 5), revenue_col='Revenue', n_cols=2):
    """
    Generates lightweight exploratory data analysis plots for each feature in the dataset.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataset containing all features
    column_descriptions : dict
        Dictionary with feature descriptions and types
    figsize : tuple, optional (default=(16, 5))
        Width, height of each row of plots
    revenue_col : str, optional (default='Revenue')
        Name of the target variable column
    n_cols : int, optional (default=2)
        Number of columns in the subplot grid
        
    Returns:
    --------
    None. Displays plots.
    """
    import matplotlib.pyplot as plt
    import seaborn as sns
    import pandas as pd
    
    # Extract feature types from column_descriptions
    numeric_features = []
    categorical_features = []
    
    for col, info in column_descriptions.items():
        if col == revenue_col:
            continue  # Skip the target variable
            
        if isinstance(info, dict):  # If using the structured dictionary format
            if info["type"] == "numeric":
                numeric_features.append(col)
            else:
                categorical_features.append(col)
        else:  # If using the string-based format
            if "Type: numeric" in info:
                numeric_features.append(col)
            else:
                categorical_features.append(col)
    
    # Function to create plots for numeric features
    def plot_numeric_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Simple histogram with mean and median lines
        sns.histplot(df[feature].dropna(), bins=30, kde=False, ax=axes[0])
        
        # Add mean line (red dotted)
        mean_val = df[feature].mean()
        axes[0].axvline(mean_val, color='red', linestyle='--', linewidth=1.5, 
                       label=f'Mean: {mean_val:.2f}')
        
        # Add median line (green dotted) - using same style as mean line
        median_val = df[feature].median()
        axes[0].axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                       label=f'Median: {median_val:.2f}')
        
        axes[0].legend(loc='best')
        axes[0].set_title(f'Distribution of {feature}')
        axes[0].set_xlabel(feature)
        
        # Right plot: Box plot by Revenue with mean and median annotations
        sns.boxplot(x=revenue_col, y=feature, data=df, ax=axes[1])
        
        # Add mean and median for each group in a single box at the top right of each bar
        for i, rev_val in enumerate([False, True]):
            group_data = df[df[revenue_col] == rev_val][feature].dropna()
            
            if len(group_data) > 0:
                group_mean = group_data.mean()
                group_median = group_data.median()
                
                # Get y-axis limits to position annotations
                ymin, ymax = axes[1].get_ylim()
                
                # Position at the top right of each box
                box_width = 0.4  # Default box width in seaborn
                annotation_x = i + box_width/2 + 0.1
                annotation_y = ymax - (ymax - ymin) * 0.1  # Position near the top
                
                # Create a single box with both mean and median
                # Use the respective colors for mean and median values
                annotation_text = f"mean: {group_mean:.2f}\nmedian: {group_median:.2f}"
                
                # Add the combined annotation box
                axes[1].text(
                    annotation_x, annotation_y,
                    annotation_text,
                    ha='left', va='top',
                    bbox=dict(facecolor='white', alpha=0.85, boxstyle='round,pad=0.3', edgecolor='gray'),
                    color='black'
                )
                
                # Add horizontal lines for mean (red) and median (green)
                # For the mean line
                axes[1].hlines(
                    y=group_mean, 
                    xmin=i-box_width/2, 
                    xmax=i+box_width/2,
                    colors='red', 
                    linestyles='dashed', 
                    linewidth=2,
                    zorder=3  # To ensure it's drawn on top of the box plot
                )
                
                # For the median line (the box plot already has a median line, but we'll add our own for consistency)
                axes[1].hlines(
                    y=group_median, 
                    xmin=i-box_width/2, 
                    xmax=i+box_width/2,
                    colors='green', 
                    linestyles='dashed', 
                    linewidth=2,
                    zorder=3  # To ensure it's drawn on top of the box plot
                )
                
        axes[1].set_title(f'{feature} by {revenue_col}')
            
        plt.tight_layout()
        plt.show()
    
    # Function to create plots for categorical features
    def plot_categorical_feature(feature):
        fig, axes = plt.subplots(1, n_cols, figsize=figsize)
        
        # Left plot: Count plot with all categories
        order = df[feature].value_counts().index
        sns.countplot(y=feature, data=df, order=order, ax=axes[0])
        axes[0].set_title(f'Count of {feature}')
        axes[0].set_ylabel(feature)
        
        # Right plot: Stacked bar chart by Revenue showing comparison to overall conversion rate
        crosstab = pd.crosstab(df[feature], df[revenue_col], normalize='index')
        
        # Simplified handling - just use the boolean values directly
        # Create the plot with colors
        colors = {True: 'gold', False: 'steelblue'}
        try:
            # Try to put True first if it exists
            if True in crosstab.columns:
                ordered_columns = [True, False]
                ordered_columns = [col for col in ordered_columns if col in crosstab.columns]
                crosstab = crosstab[ordered_columns]
            
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], 
                         color=[colors.get(col, 'gray') for col in crosstab.columns])
        except:
            # Fallback if something goes wrong
            crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
        
        # Calculate overall proportion of True in the dataset
        overall_true_proportion = df[revenue_col].mean()
        
        # Add a reference line for the overall proportion at 0.85 instead of 0.15
        # This makes it easier to compare with the True portion
        axes[1].axvline(x=0.85, color='red', linestyle='--', linewidth=1.5,
                        label=f'Overall True: {overall_true_proportion:.2f}')
        
        axes[1].legend(loc='lower right')
        axes[1].set_title(f'Conversion Rate by {feature} vs. Overall Rate')
        axes[1].set_xlabel('Proportion')
        axes[1].set_ylabel(feature)
        
        plt.tight_layout()
        plt.show()
    
    # Function to show basic stats before plotting
    def plot_feature(feature):
        print(f"\n{'='*40}")
        
        # Extract and print feature description
        if isinstance(column_descriptions[feature], dict):
            desc = column_descriptions[feature]["description"]
        else:
            desc = column_descriptions[feature].split("Type:")[0].strip()
            
        print(f"Feature: {feature}")
        print(f"Description: {desc}")
        print(f"Missing Values: {df[feature].isna().sum()} ({df[feature].isna().mean():.2%})")
        
        if feature in numeric_features:
            # Get the values for statistics
            min_val = df[feature].min()
            max_val = df[feature].max()
            mean_val = df[feature].mean()
            median_val = df[feature].median()
            
            # Print statistics with the requested format
            print("Basic Statistics:")
            print(f" Min      Max        Mean  Median")
            print(f" {min_val} {max_val} {mean_val} {median_val}")
            
            plot_numeric_feature(feature)
        else:
            # Print only top categories
            value_counts = df[feature].value_counts()
            print("\nTop 5 Categories:")
            print(value_counts.head(5).to_string())
            
            plot_categorical_feature(feature)
    
    # Plot each feature
    for feature in numeric_features + categorical_features:
        plot_feature(feature)

In [ ]:
plot_feature_eda(session_data_df, column_descriptions)

In [ ]:
session_data_df.columns

In [ ]:
plot_feature_eda(session_data_df, column_descriptions, features_to_plot=['BounceRates', 'Administrative'], log_transform=True)

In [ ]:
def analyze_feature_classes(df, feature_names, class_values, target_col='Revenue'):
    """
    Analyzes specified classes within features and compares their conversion rates.
    
    Parameters:
    -----------
    df : pandas DataFrame
        The dataset containing the features and target column
    feature_names : str or list
        The name(s) of the feature column(s) to analyze
    class_values : str, list, or dict
        Class values to analyze within each feature.
        If str or list: The same values will be used for all features
        If dict: Keys are feature names and values are lists of class values to analyze
    target_col : str, optional (default='Revenue')
        The name of the target/conversion column
        
    Returns:
    --------
    None. Prints analysis and displays visualizations.
    """
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns
    
    # Normalize feature_names to list
    if isinstance(feature_names, str):
        feature_names = [feature_names]
    
    # Handle different formats of class_values
    if isinstance(class_values, dict):
        # Dictionary mapping features to their classes
        feature_class_map = class_values
    else:
        # Convert to list if string
        if isinstance(class_values, str) or not isinstance(class_values, list):
            class_values = [class_values]
        
        # Create a map with the same classes for all features
        feature_class_map = {feature: class_values for feature in feature_names}
    
    # Validate features
    for feature in feature_names:
        if feature not in df.columns:
            print(f"Error: Feature '{feature}' not found in the dataframe")
            return
    
    # Validate target column
    if target_col not in df.columns:
        print(f"Error: Target column '{target_col}' not found in the dataframe")
        return
    
    # Get overall dataset stats
    total_count = len(df)
    total_converted = (df[target_col] == True).sum()
    overall_conversion_rate = total_converted / total_count
    
    # Define colors to match existing visuals
    colors = {True: 'gold', False: 'steelblue'}
    
    # Analyze each feature
    for feature_name in feature_names:
        # Get classes to analyze for this feature
        class_list = feature_class_map.get(feature_name, [])
        
        # Filter class list to only include classes that exist in this feature
        valid_classes = []
        for cls in class_list:
            if cls in df[feature_name].values:
                valid_classes.append(cls)
            else:
                print(f"Warning: Class '{cls}' not found in feature '{feature_name}'")
        
        if not valid_classes:
            print(f"No valid classes to analyze for feature '{feature_name}'")
            continue
        
        # Create DataFrame to store results for this feature
        results = []
        
        # Print header
        print(f"\n{'='*40}")
        print(f"Feature: {feature_name}")
        print(f"{'='*40}")
        
        # Analyze each class
        for class_value in valid_classes:
            # Create filter for this class
            class_filter = df[feature_name] == class_value
            
            # Apply filter
            class_df = df[class_filter]
            
            # Get counts
            class_count = len(class_df)
            class_converted = (class_df[target_col] == True).sum()
            
            # Calculate metrics
            class_ratio = class_count / total_count if total_count > 0 else 0
            class_conversion_rate = class_converted / class_count if class_count > 0 else 0
            converted_ratio = class_converted / total_converted if total_converted > 0 else 0
            
            # Store results
            results.append({
                'Class': str(class_value),  # Convert to string for consistent display
                'Count': class_count,
                'Dataset_Ratio': class_ratio,
                'Converted_Count': class_converted,
                'Conversion_Rate': class_conversion_rate,
                'Portion_of_All_Conversions': converted_ratio
            })
            
            # Print individual class analysis
            print(f"\nClass: '{class_value}'")
            print(f"Total rows: {class_count} ({class_ratio:.2%} of all data)")
            print(f"Converted rows: {class_converted} ({class_conversion_rate:.2%} conversion rate within subset)")
            print(f"Portion of all conversions: {class_converted}/{total_converted} ({converted_ratio:.2%})")
        
        # Convert results to DataFrame for visualization
        results_df = pd.DataFrame(results)
        
        if len(results_df) > 0:
            # Create figure with 1 row, 2 columns
            fig, axes = plt.subplots(1, 2, figsize=(16, 5))
            
            # Left plot: Count plot with classes
            # Sort by count for better visualization
            results_df_sorted = results_df.sort_values('Count', ascending=False)
            sns.barplot(y='Class', x='Count', data=results_df_sorted, ax=axes[0])
            axes[0].set_title(f'Count of {feature_name}')
            axes[0].set_ylabel(feature_name)
            
            # Right plot: Use crosstab approach matching your plot_feature_eda function
            # First create a temporary dataframe with just this feature and the filtered classes
            classes_filter = df[feature_name].isin(valid_classes)
            temp_df = df[classes_filter][[feature_name, target_col]].copy()
            
            # Create the crosstab
            crosstab = pd.crosstab(temp_df[feature_name], temp_df[target_col], normalize='index')
            
            # Ensure all valid classes are in the crosstab index (even if they don't appear in the filtered data)
            for cls in valid_classes:
                if cls not in crosstab.index:
                    # Add a row for this class with zeros
                    if len(crosstab.columns) > 0:
                        new_row = pd.Series(0, index=crosstab.columns)
                        crosstab.loc[cls] = new_row
                    else:
                        # If crosstab is empty, add with placeholder columns
                        crosstab.loc[cls, False] = 1.0  # 100% False

            # Make sure both True and False columns exist
            if True not in crosstab.columns:
                crosstab[True] = 0
            if False not in crosstab.columns:
                crosstab[False] = 1  # If no False column, all are True

            # Sort the crosstab index to match the order of valid_classes
            crosstab = crosstab.reindex(valid_classes)
            
            try:
                # Try to put True first if it exists
                if True in crosstab.columns:
                    ordered_columns = [True, False]
                    ordered_columns = [col for col in ordered_columns if col in crosstab.columns]
                    crosstab = crosstab[ordered_columns]
                
                crosstab.plot(kind='barh', stacked=True, ax=axes[1],
                             color=[colors.get(col, 'gray') for col in crosstab.columns])
            except:
                # Fallback if something goes wrong, using viridis colormap like in your function
                crosstab.plot(kind='barh', stacked=True, ax=axes[1], colormap='viridis')
            
            # Calculate overall proportion of True in the dataset
            overall_true_proportion = df[target_col].mean()
            
            # Add a reference line at 0.85 exactly as in your function
            axes[1].axvline(x=0.85, color='red', linestyle='--', linewidth=1.5,
                           label=f'Overall True: {overall_true_proportion:.2f}')
            
            axes[1].legend(loc='lower right')
            axes[1].set_title(f'Conversion Rate by {feature_name} vs. Overall Rate')
            axes[1].set_xlabel('Proportion')
            axes[1].set_ylabel(feature_name)
            
            plt.tight_layout()
            plt.show()
        
            # Print summary comparison table
            print("\nSummary Table:")
            summary_df = results_df[['Class', 'Count', 'Dataset_Ratio', 'Conversion_Rate']]
            
            # Add overall row
            overall_row = pd.DataFrame([{
                'Class': 'Overall Dataset', 
                'Count': total_count,
                'Dataset_Ratio': 1.0,
                'Conversion_Rate': overall_conversion_rate
            }])
            
            summary_df = pd.concat([summary_df, overall_row], ignore_index=True)
            
            # Format percentages for display
            summary_df['Dataset_Ratio'] = summary_df['Dataset_Ratio'].apply(lambda x: f"{x:.2%}")
            summary_df['Conversion_Rate'] = summary_df['Conversion_Rate'].apply(lambda x: f"{x:.2%}")
            
            print(summary_df.to_string(index=False))

In [2]:
import pandas as pd

dict_stuff = {'A' : [True, False]}

df_stuff = pd.DataFrame(dict_stuff)

In [3]:
df_stuff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      bool
dtypes: bool(1)
memory usage: 134.0 bytes

In [ ]:
df_stuff.astype(object)

       A
0   True
1  False

In [5]:
df_stuff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      bool
dtypes: bool(1)
memory usage: 134.0 bytes

The stated goal of the company in the future is to apply this AI model in real time in order to identify customers that will convert.

It's not entirely clear what they actually want to do with these users.